
drop table if exists ac_user;

create table ac_user (
	id bigint generated by default as identity,
	loginname varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	email varchar(128)  null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	registerdate timestamp not null,
	primary key (id)
);

INSERT INTO ac_user (id, loginname, name, password, email, salt, roles, registerdate) VALUES
	(1, 'admin', 'admin', '7bef2b21bb29f74eace63872e43b96fd2b1fed92', '', 'c396b702f7c09949', 'user', '2012-12-20 10:44:59')
